In [181]:
#Importong libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.decomposition import TruncatedSVD

In [150]:
#Reading the data
data = pd.read_csv("spam.csv", encoding = 'latin-1')

In [151]:
#Checing the data
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [152]:
data.tail()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [153]:
'''
 Columns "Unnamed: 2", "Unnamed: 3" and "Unnamed: 4" have some messy data in it, and both in .head() and .tail() are shown columns that have NaN values.
 So we check if there is any column that does not have NaN data, and if the data is not important we will remove the columns.
'''

'\n Columns "Unnamed: 2", "Unnamed: 3" and "Unnamed: 4" have some messy data in it, and both in .head() and .tail() are shown columns that have NaN values.\n So we check if there is any column that does not have NaN data, and if the data is not important we will remove the columns.\n'

In [154]:
data["Unnamed: 2"].count()

np.int64(50)

In [155]:
data.value_counts(subset = "Unnamed: 2", dropna=False)

Unnamed: 2
NaN                                                                                                                                                 5522
 bt not his girlfrnd... G o o d n i g h t . . .@"                                                                                                      3
 PO Box 5249                                                                                                                                           2
 don't miss ur best life for anything... Gud nyt..."                                                                                                   2
 but dont try to prove it..\" .Gud noon...."                                                                                                           2
GN                                                                                                                                                     2
this wont even start........ Datz confidence.."                                                                                                        2
 Gud night...."                                                                                                                                        1
 GOD said                                                                                                                                              1
 But at d end my love compromised me for everything:-(\".. Gud mornin:-)"                                                                              1
 ENJOYIN INDIANS AT THE MO..yeP. SaLL gOoD HehE ;> hows bout u shexy? Pete Xx\""                                                                       1
 Dont Come Near My Body..!! Bcoz My Hands May Not Come 2 Wipe Ur Tears Off That Time..!Gud ni8"                                                        1
 PO Box 1146 MK45 2WT (2/3)"                                                                                                                           1
 I'll come up"                                                                                                                                         1
 I don't mind                                                                                                                                          1
 HOWU DOIN? FOUNDURSELF A JOBYET SAUSAGE?LOVE JEN XXX\""                                                                                               1
 HAD A COOL NYTHO                                                                                                                                      1
 HOPE UR OK... WILL GIVE U A BUZ WEDLUNCH. GO OUTSOMEWHERE 4 ADRINK IN TOWN..CUD GO 2WATERSHD 4 A BIT? PPL FROMWRK WILL BTHERE. LOVE PETEXXX.\""       1
 b'coz nobody will fight for u. Only u &amp; u have to fight for ur self &amp; win the battle. -VIVEKANAND- G 9t.. SD.."                               1
 SHE SHUDVETOLD U. DID URGRAN KNOW?NEWAY                                                                                                               1
 but watever u shared should be true\"...."                                                                                                            1
 hopeSo hunny. i amnow feelin ill & ithink i may have tonsolitusaswell! damn iam layin in bedreal bored. lotsof luv me xxxx\""                         1
 its a miracle to Love a person who can't Love anyone except U...\" Gud nyt..."                                                                        1
 just as a shop has to give a guarantee on what they sell. B. G."                                                                                      1
 justthought iåÕd sayhey! how u doin?nearly the endof me wk offdam nevamind!We will have 2Hook up sn if uwant m8? loveJen x.\""                        1
 always give response 2 who cares 4 U\"... Gud night..swt dreams..take care"                                                                           1
 but dont try to prove\" ..... Gud mrng..."                                                                                                            1
 \"It is d wonderful fruit that a tree gives when it is being hurt by a stone.. Good night......"                                                      1
 that's the tiny street where the parking lot is"                                                                                                      1
 smoke hella weed\""                                                                                                                                   1
 like you are the KING\"...! OR \"Walk like you Dont care                                                                                              1
 the person is definitely special for u..... But if the person is so special                                                                           1
 we made you hold all the weed\""                                                                                                                      1
.;-):-D"                                                                                                                                               1
 wanted to say hi. HI!!!\" Stop? Send STOP to 62468"                                                                                                   1
 the toughest is acting Happy with all unspoken pain inside..\""                                                                                       1
JUST GOT PAYED2DAY & I HAVBEEN GIVEN Aå£50 PAY RISE 4MY WORK & HAVEBEEN MADE PRESCHOOLCO-ORDINATOR 2I AM FEELINGOOD LUV\""                             1
DEVIOUSBITCH.ANYWAY                                                                                                                                    1
JUST REALLYNEED 2DOCD.PLEASE DONTPLEASE DONTIGNORE MYCALLS                                                                                             1
PROBPOP IN & CU SATTHEN HUNNY 4BREKKIE! LOVE JEN XXX. PSXTRA LRG PORTIONS 4 ME PLEASE \""                                                              1
\" not \"what i need to do.\""                                                                                                                         1
Well there's still a bit left if you guys want to tonight                                                                                              1
just been in bedbut mite go 2 thepub l8tr if uwana mt up?loads a luv Jenxxx.\""                                                                        1
u hav2hear it!c u sn xxxx\""                                                                                                                           1
Name: count, dtype: int64

In [156]:
data["Unnamed: 3"].count()

np.int64(12)

In [157]:
data.value_counts(subset = "Unnamed: 3", dropna = False)

Unnamed: 3
NaN                                           5560
GE                                               2
 MK17 92H. 450Ppw 16"                            2
 TX 4 FONIN HON                                  1
 ILLSPEAK 2 U2MORO WEN IM NOT ASLEEP...\""       1
 why to miss them                                1
 \"OH No! COMPETITION\". Who knew                1
IåÕL CALL U\""                                   1
U NO THECD ISV.IMPORTANT TOME 4 2MORO\""         1
i wil tolerat.bcs ur my someone..... But         1
whoever is the KING\"!... Gud nyt"               1
Name: count, dtype: int64

In [158]:
data["Unnamed: 4"].count()

np.int64(6)

In [159]:
data.value_counts(subset = "Unnamed: 4", dropna = False)

Unnamed: 4
NaN                                                         5566
GNT:-)"                                                        2
 Never comfort me with a lie\" gud ni8 and sweet dreams"       1
 CALL 2MWEN IM BK FRMCLOUD 9! J X\""                           1
 one day these two will become FREINDS FOREVER!"               1
 just Keep-in-touch\" gdeve.."                                 1
Name: count, dtype: int64

In [160]:
'''
 As we see there is no important data to be used, so we will delete the columns.
'''

'\n As we see there is no important data to be used, so we will delete the columns.\n'

In [161]:
#Checking if the deletion prooccess is what we need
data.drop(columns = ["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"])

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [162]:
#As it is the way we want the data to be deleted, now we actually delete the data
data.drop(columns = ["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], inplace = True)

In [163]:
#Checking if the deletion was successful
data

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [164]:
#Converting text data into numbers: ham -> 1, spam -> -1
data.v1 = data.v1.map({"ham": 1, "spam": -1})

In [165]:
#Checking if the convertion was successful
data

      v1                                                 v2
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2     -1  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...
...   ..                                                ...
5567  -1  This is the 2nd time we have tried 2 contact u...
5568   1              Will Ì_ b going to esplanade fr home?
5569   1  Pity, * was in mood for that. So...any other s...
5570   1  The guy did some bitching but I acted like i'd...
5571   1                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [166]:
#Splitting data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(data.v2, data.v1, test_size = 0.2, random_state = 1, stratify = data.v1)

In [167]:
tfidf = TfidfVectorizer(stop_words = "english")

In [168]:
X_train_tfidf = tfidf.fit_transform(X_train)

In [169]:
X_test_tfidf = tfidf.transform(X_test)

In [170]:
#Initializing SVM
sv = SVC(C = 3.0, kernel = 'linear', gamma = 1.0)

In [179]:
#Fitting the model
sv.fit(X_train_tfidf, y_train)

SVC(C=3.0, gamma=1.0, kernel='linear')

In [180]:
#Predicting and checking the accuracy score
y_pred = sv.predict(X_test_tfidf)
print(f"The prediction accuracy of the model using the testing dataset is: {100 * accuracy_score(y_pred, y_test):.3f}")

The prediction accuracy of the model using the testing dataset is: 98.475

In [ ]:
'''
As the dataset is 5000 dimensional, it is hard to visualize data pretty well so this time I am not going to do it.
'''